### ISSUE TITLE
Uncaught TypeError: TesseractWorker is not a constructor

### ISSUE THREAD

**Issue by rmbarros** [jeromewu/tesseract.js-vue-app#2]
Trying to run the code straight after cloning throws an error:

Uncaught TypeError: tesseract_js__WEBPACK_IMPORTED_MODULE_0__.TesseractWorker is not a constructor

**Comment by jeromewu** [comment]
Please try again with the latest version, I have done some patch.

**Comment by jeromewu** [comment]
Close for inactivity.
