### ISSUE TITLE
Progress message not showing

### ISSUE THREAD

**Issue by ymoc1699** [jeromewu/tesseract.js-vue-app#3]
Hello, sir. I'm having a problem using this in vue. I included a loading message which is "Scanning image" + the percentage of the progress. The whole package of yours works, I thank you for that btw, but my problem is, the message suddenly becomes null, whenever I try to use a validation for my form which has this OCR. I am using vee validate to prevent a user from using the OCR form. Any example of ocr that includes a validation?

**Comment by jeromewu** [comment]
Sorry it is not easy to understand your problem, can you provide some sample code?

**Comment by ymoc1699** [comment]
Oh, thanks for the reply sir. It's already fine. However may I ask a question? Is confidence equivalent to the accuracy rate of the extracted text from an image? If not, does tesseract.js actually offer accuracy percentage rate? Thank you!

**Comment by jeromewu** [comment]
It is OK to see confidence as the indicator of accuracy rate and I think it is the closest one you can find so far.
